Завдання. Робота з бібліотекою Numpy.
Лабораторна робота 1.
Виконала студентка ФІТ 3-9 Бессараб Марія

In [ ]:
import numpy as np

# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення
vector = np.arange(1, 21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as np

# 2. Створіть двовимірний масив 4x4, заповніть його одиницями та виведіть його значення
matrix_4x4 = np.ones((4,4))
print(matrix_4x4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
random_matrix = np.random.uniform(-1, 1, (5, 5))
print(random_matrix)

[[-0.01586124  0.89812613  0.73502416 -0.6892741   0.68108542]
 [-0.68183881 -0.35208452 -0.27291578  0.37010744 -0.11369968]
 [ 0.32185257  0.45190968  0.86837677  0.22856999  0.06669892]
 [-0.21773021 -0.77251649 -0.81908084 -0.90017028  0.49271192]
 [-0.49713933  0.01066409 -0.87385525  0.31179261  0.56205306]]


In [ ]:
import numpy as np

#4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
random_matrix_3x3 = np.random.rand(3,3)
print(random_matrix_3x3)

[[0.38490526 0.23457263 0.86599591]
 [0.41902523 0.43482212 0.75136692]
 [0.14158647 0.44350735 0.72744385]]


In [ ]:
import numpy as np

#5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

a = np.random.randint(1, 21, 6)
b = np.random.randint(1, 21, 6)

print("Масив A:", a)
print("Масив B:", b)
print("Додавання A + B:", a + b)
print("Віднімання A - B:", a - b)
print("Множення A * B:", a * b)


Масив A: [ 7 19 18  7 17 19]
Масив B: [ 1  9  2  7 19 16]
Додавання A + B: [ 8 28 20 14 36 35]
Віднімання A - B: [ 6 10 16  0 -2  3]
Множення A * B: [  7 171  36  49 323 304]


In [ ]:
import numpy as np

# 6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

A = np.random.randint(1, 6, (3, 2))
B = np.random.randint(1, 6, (2, 4))

C = A @ B
print("Матриця A:\n", A)
print("Матриця B:\n", B)
print("Добуток A @ B:\n", C)



Матриця A:
 [[3 1]
 [1 5]
 [5 3]]
Матриця B:
 [[1 2 2 2]
 [1 4 3 4]]
Добуток A @ B:
 [[ 4 10  9 10]
 [ 6 22 17 22]
 [ 8 22 19 22]]


In [ ]:
import numpy as np

# 7.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

matrix_3x3 = np.random.rand(3, 3)
transposed_matrix = matrix_3x3.T

print("Оригінальна матриця:\n", matrix_3x3)
print("Транспонована матриця:\n", transposed_matrix)

Оригінальна матриця:
 [[0.35852414 0.86283637 0.67322888]
 [0.75069845 0.50215612 0.3510115 ]
 [0.57713701 0.55467934 0.60077069]]
Транспонована матриця:
 [[0.35852414 0.75069845 0.57713701]
 [0.86283637 0.50215612 0.55467934]
 [0.67322888 0.3510115  0.60077069]]


In [ ]:
import numpy as np

# 8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))

difference = A - B

print("Мартиця А:\n", A)
print("Мартиця B:\n", B)
print("Різниця:\n", difference)

Мартиця А:
 [[ 8  2  5]
 [ 1  8  5]
 [10  5  5]]
Мартиця B:
 [[9 9 1]
 [6 2 8]
 [9 5 9]]
Різниця:
 [[-1 -7  4]
 [-5  6 -3]
 [ 1  0 -4]]


In [ ]:
import numpy as np

# 9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

A = np.random.randint(-5, 6, (3, 3))
B = np.random.randint(-5, 6, (3, 3))

product = A @ B  # або np.dot(A, B)

print("Мартиця А:\n", A)
print("Мартиця B:\n", B)
print("Добуток A @ B:\n", product)

Мартиця А:
 [[-4 -2  4]
 [ 1 -3 -2]
 [-4  3 -1]]
Мартиця B:
 [[ 4 -5 -1]
 [ 4 -1 -5]
 [ 0  3  3]]
Добуток A @ B:
 [[-24  34  26]
 [ -8  -8   8]
 [ -4  14 -14]]


In [ ]:
import numpy as np

# 10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

matrix = np.random.uniform(-1, 1, (3, 3))
row_sums = np.sum(matrix, axis=1 ).reshape(-1, 1)

print("Матриця А:\n", matrix)
print("Вектор стовпчик сум рядків:\n", row_sums)




Матриця А:
 [[ 0.17106637 -0.96864105 -0.22845237]
 [-0.84078455 -0.09228859 -0.53381041]
 [ 0.03018386  0.57709168 -0.16941798]]
Вектор стовпчик сум рядків:
 [[-1.02602705]
 [-1.46688354]
 [ 0.43785756]]
